@startuml

class CustomerService {
    +createTicket(factory: TicketFactory): Ticket
    +resolveTicket(ticket: Ticket, strategy: Resolution)
}

interface Ticket
interface Resolution

CustomerService --> Ticket
CustomerService --> Resolution
CustomerService --> TicketFactory

@enduml