@startuml

class CustomerService {
    +createTicket(type, data)
    +resolveTicket(ticket: Ticket, strategy: Resolution)
    +notifyDepartments(ticket: Ticket)
}

class ServiceTicketCreator
interface Ticket
interface DepartmentNotifier
interface Resolution

CustomerService --> ServiceTicketCreator
CustomerService --> Ticket
CustomerService --> DepartmentNotifier
CustomerService --> Resolution
@enduml
